version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mafia-server"
    volumes:
      - ./:/src
    container_name: mafia-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - db_network
    links:
      - db
    restart: always

  db:
    image: "${POSTGRES_IMAGE}"
    container_name: mafia-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
    restart: always

volumes:
  db-data:

networks:
  db_network:
    driver: bridge